# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 16:59
from __future__ import unicode_literals

import auctionDjango.auction_validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('timestamp', models.DateTimeField(verbose_name='date published')),
                ('deadline', models.DateTimeField(validators=[auctionDjango.auction_validators.validate_deadline], verbose_name='deadline')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('auction_winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctionDjango.Item'),
        ),
        migrations.AddField(
            model_name='auction',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
