# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionDjango', '0004_auto_20161105_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='deadline',
            field=models.DateTimeField(default=None, verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='timestamp',
            field=models.DateTimeField(default=None, verbose_name='date published'),
        ),
    ]
